### ISSUE TITLE
Can it be running on production release

### ISSUE THREAD

**Issue by aminerol** [Zenklub/react-native-firebase-perf-tracer#2]
Hey thanks for this library, it got exactly what i need but i was just wondering if this can work as it should in production.
knowing that react profiler is not available in production release.
if so can you guys do an example app where you showcase how we can use it in production

**Comment by erick-martins** [comment]
Adding this to your `.babelrc` should be enough to activate it for production

```json
{
  "presets": ["module:metro-react-native-babel-preset"],
  "plugins": [
    ["module-resolver", {
      "root": ["./"],
      "alias": {
        "ReactNativeRenderer-prod": "./node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-profiling",
        "scheduler/tracing": "scheduler/tracing-profiling"
      }
    }]
  ]
}
```

It will be better documented soon

**Comment by rxrossi** [comment]
Hi @aminerol, I see that you have published the lib on NPM, would you transfer it to us?

**Comment by aminerol** [comment]
Yes sure, sorry had to publish it without your permission since I couldnt find it on NPM, what is your npm username?

**Comment by rxrossi** [comment]
No problem and thanks, my npm username is: rx.rossi
